server.port=8082

appid=1a4288033bc8799e6182081e17d3144c
url.weather=https://api.openweathermap.org/data/2.5/weather

spring.application.name=weather-info-service

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
